version: "3.9"

services:
  nnunetv2:
    container_name: nnunetv2
    image: nnunetv2
    build:
      context: .
      dockerfile: deployment/Dockerfile
    volumes:
      - ./input:/nnunet-ms-segmentation/input/
      - ./output:/nnunet-ms-segmentation/output/
    command: /bin/sh predict.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]